In [1]:
import pandas as pd

In [3]:
my_books = pd.read_csv("./dataset/liked_books.csv", index_col=0)

In [4]:
my_books

,user_id,book_id,rating,title
0,-1,2517439,5,"The Forever War (The Forever War, #1)"
1,-1,113576,5,The Smartest Guys in the Room: The Amazing Ris...
2,-1,35100,5,Battle Cry of Freedom
3,-1,228221,5,The Mask of Command
5,-1,17662739,5,"2001: A Space Odyssey (Space Odyssey, #1)"
6,-1,356824,5,India After Gandhi: The History of the World's...
7,-1,12125412,5,The Lady or the Tiger?: and Other Logic Puzzles
8,-1,139069,5,Endurance: Shackleton's Incredible Voyage
10,-1,76680,5,"Foundation (Foundation, #1)"
11,-1,1898,5,Into Thin Air: A Personal Account of the Mount...
12,-1,5096865,5,In Cold Blood
13,-1,228665,5,"The Eye of the World (The Wheel of Time, #1)"
17,-1,437143,5,A Short History of Nearly Everything
18,-1,18949861,5,Contact
19,-1,2913377,5,The Name of the Wind (The Kingkiller Chronicl...
20,-1,1215032,5,The Wise Man's Fear (The Kingkiller Chronicle...
21,-1,883438,5,East of Eden
22,-1,5578108,5,From Colony to Superpower: U.S. Foreign Relati...
23,-1,128029,5,A Thousand Splendid Suns
24,-1,77203,5,The Kite Runner
25,-1,5439,5,Interpreter of Maladies
26,-1,1685995,5,Dune (Dune #1)
27,-1,6448772,5,"Quantum: Einstein, Bohr, and the Great Debate ..."
527,-1,8161140,1,On the Beach
528,-1,28187,1,The Lightning Thief (Percy Jackson and the Ol...
531,-1,25659450,1,Arkwright
532,-1,82599,1,Rabbits: A Novel

In [5]:
my_books["book_id"] = my_books["book_id"].astype(str)

In [7]:
csv_book_mapping = {}

with open("./dataset/book_id_map.csv", 'r') as f:
    while True:
        line = f.readline()
        if not line:
            break
        csv_id, book_id = line.strip().split(",")
        csv_book_mapping[csv_id] = book_id

In [8]:
book_set = set(my_books["book_id"])

In [9]:
book_set

{'113576',
 '12125412',
 '1215032',
 '128029',
 '139069',
 '1685995',
 '17662739',
 '18949861',
 '1898',
 '228221',
 '228665',
 '2517439',
 '25659450',
 '28187',
 '2913377',
 '35100',
 '356824',
 '437143',
 '5096865',
 '5439',
 '5578108',
 '6448772',
 '76680',
 '77203',
 '8161140',
 '82599',
 '883438'}

In [13]:
overlap_users = {}

with open("./dataset/goodreads_interactions.csv") as f:
    while True:
        line = f.readline()
        if not line:
            break
        user_id, csv_id, _, rating, _ = line.strip().split(",") 
        book_id = csv_book_mapping.get(csv_id)

        if book_id in book_set:
            if user_id not in overlap_users:
                overlap_users[user_id] = 1
            else:
                overlap_users[user_id] += 1

In [14]:
len(overlap_users)

316341

In [15]:
# Filtering out users who are genuine by the number of books they've read.
filtered_overlap_users = set([k for k in overlap_users if overlap_users[k] > my_books.shape[0]/5])
filtered_overlap_users

{'129368',
 '250591',
 '41530',
 '37831',
 '179174',
 '66901',
 '365778',
 '406010',
 '360934',
 '97483',
 '46065',
 '212743',
 '291920',
 '170481',
 '134378',
 '90398',
 '24630',
 '288072',
 '48578',
 '58645',
 '74145',
 '316845',
 '104621',
 '159518',
 '351008',
 '158745',
 '296219',
 '355644',
 '72295',
 '272682',
 '278502',
 '79329',
 '73800',
 '35479',
 '77376',
 '134632',
 '151518',
 '190137',
 '222007',
 '89043',
 '144701',
 '302187',
 '397497',
 '2351',
 '382398',
 '408301',
 '53190',
 '14367',
 '442043',
 '61267',
 '23351',
 '106972',
 '2111',
 '339532',
 '414788',
 '275357',
 '219620',
 '329213',
 '334784',
 '72562',
 '71517',
 '16569',
 '435197',
 '321411',
 '61342',
 '397366',
 '285907',
 '427556',
 '180123',
 '359034',
 '219165',
 '279139',
 '11961',
 '127686',
 '309603',
 '201825',
 '359399',
 '380533',
 '256044',
 '999',
 '217919',
 '131193',
 '296208',
 '416683',
 '176151',
 '236792',
 '416740',
 '31554',
 '41551',
 '52411',
 '113970',
 '118777',
 '309155',
 '107125',
 '369128',
 '380165',
 '169303',
 '394890',
 '340869',
 '401224',
 '26299',
 '360552',
 '284597',
 '190707',
 '414833',
 '419543',
 '46745',
 '18356',
 '186520',
 '292632',
 '292541',
 '233779',
 '339622',
 '41250',
 '196764',
 '98226',
 '275859',
 '254583',
 '224978',
 '117510',
 '279763',
 '117798',
 '303460',
 '5928',
 '426793',
 '304312',
 '77779',
 '281363',
 '439093',
 '286847',
 '8358',
 '256850',
 '395729',
 '56922',
 '202585',
 '138855',
 '279728',
 '188738',
 '99953',
 '332847',
 '385920',
 '12163',
 '18829',
 '439368',
 '375494',
 '189756',
 '205978',
 '435739',
 '428890',
 '18666',
 '119660',
 '396456',
 '441504',
 '188240',
 '66948',
 '219681',
 '350007',
 '320562',
 '133624',
 '35644',
 '183283',
 '94096',
 '292619',
 '154555',
 '431265',
 '66337',
 '288079',
 '86215',
 '329154',
 '8543',
 '341255',
 '275263',
 '398495',
 '134712',
 '202334',
 '260673',
 '379261',
 '9854',
 '4728',
 '47680',
 '41495',
 '212520',
 '431858',
 '31295',
 '153933',
 '356170',
 '281364',
 '114191',
 '201824',
 '149480',
 '97769',
 '12146',
 '314868',
 '24707',
 '322065',
 '85031',
 '280135',
 '182231',
 '196843',
 '141862',
 '223588',
 '400288',
 '206208',
 '106155',
 '52441',
 '43546',
 '137623',
 '341674',
 '343421',
 '135197',
 '387783',
 '206278',
 '210968',
 '355817',
 '328802',
 '251068',
 '239651',
 '90368',
 '233718',
 '422438',
 '105106',
 '432106',
 '410594',
 '75393',
 '303759',
 '156575',
 '16170',
 '289460',
 '142485',
 '43036',
 '172303',
 '374995',
 '271757',
 '328464',
 '92409',
 '27370',
 '1793',
 '131378',
 '208670',
 '157085',
 '71467',
 '207319',
 '252621',
 '276048',
 '372715',
 '207009',
 '2794',
 '45547',
 '287639',
 '107149',
 '70756',
 '404509',
 '59545',
 '166009',
 '192513',
 '12643',
 '380233',
 '127869',
 '89297',
 '191168',
 '275620',
 '256694',
 '68007',
 '16469',
 '125027',
 '75011',
 '381245',
 '173501',
 '391716',
 '874',
 '358468',
 '412985',
 '241058',
 '115845',
 '124550',
 '272560',
 '49949',
 '302621',
 '193532',
 '440851',
 '437849',
 '73840',
 '151091',
 '65620',
 '259787',
 '127427',
 '81181',
 '213917',
 '1625',
 '138215',
 '179614',
 '109959',
 '259607',
 '9891',
 '290971',
 '333831',
 '287752',
 '415475',
 '25465',
 '435828',
 '285505',
 '70338',
 '111126',
 '117133',
 '287913',
 '13713',
 '155070',
 '68711',
 '421933',
 '426679',
 '274180',
 '434690',
 '102500',
 '156384',
 '187387',
 '187787',
 '234505',
 '234957',
 '21682',
 '352321',
 '392407',
 '69845',
 '206612',
 '285132',
 '181166',
 '216084',
 '109641',
 '273830',
 '245925',
 '194850',
 '344652',
 '407806',
 '83856',
 '422451',
 '323691',
 '118262',
 '32978',
 '3653',
 '257189',
 '224224',
 '166783',
 '25225',
 '420242',
 '439423',
 '361921',
 '83699',
 '146289',
 '122275',
 '220149',
 '106200',
 '437147',
 '432435',
 '194026',
 '341472',
 '435038',
 '88542',
 '417370',
 '325795',
 '103934',
 '61868',
 '212315',
 '350392',
 '41913',
 '167166',
 '415464',
 '353492',
 '354637',
 '133140',
 '406798',
 '352785',
 '178255',
 '368287',
 '99743',
 '324338',
 '193569',
 '71809',
 '120520',
 '46925',
 '278080',
 '324336',
 '165859',
 '292112',
 '439446',
 '345317',
 '164901',
 '118527',
 '123303',
 '229036',
 '411458',
 '154566',
 '118202',
 '63986',
 '285683',
 '57557',
 '165342',
 '437356',
 '53462',
 '254700',
 '37206',
 '275162',
 '264166',
 '302410',
 '190142',
 '433999',
 '86520',
 '910',
 '107469',
 '434757',
 '299096',
 '173440',
 '171173',
 '353447',
 '338778',
 '414737',
 '276392',
 '152909',
 '145072',
 '26859',
 '14119',
 '418123',
 '279176',
 '36497',
 '221523',
 '712588',
 '19740',
 '405916',
 '279427',
 '6224',
 '76172',
 '80774',
 '404284',
 '316762',
 '177805',
 '431011',
 '413655',
 '58683',
 '17130',
 '305003',
 '195917',
 '431632',
 '248513',
 '8250',
 '73298',
 '393822',
 '212789',
 '416533',
 '195992',
 '129379',
 '295780',
 '264517',
 '158801',
 '195444',
 '319755',
 '295763',
 '293992',
 '187520',
 '323006',
 '164885',
 '6851',
 '177529',
 '218313',
 '386387',
 '189111',
 '222962',
 '72573',
 '396783',
 '430954',
 '334670',
 '268800',
 '143017',
 '310443',
 '363069',
 '389267',
 '390588',
 '112290',
 '340318',
 '237528',
 '431433',
 '141207',
 '108804',
 '279457',
 '352790',
 '58998',
 '67989',
 '24508',
 '21548',
 '48163',
 '184022',
 '399754',
 '212566',
 '313659',
 '89823',
 '75183',
 '203547',
 '284764',
 '130849',
 '75382',
 '235603',
 '39660',
 '9635',
 '190655',
 '38382',
 '260993',
 '120432',
 '405487',
 '324987',
 '6629',
 '403770',
 '120020',
 '177133',
 '313798',
 '4133',
 '123151',
 '70883',
 '78604',
 '343813',
 '362948',
 '243721',
 '422227',
 '127612',
 '138647',
 '43994',
 '252105',
 '289977',
 '184772',
 '439355',
 '399673',
 '264623',
 '119989',
 '10482',
 '283058',
 '5284',
 '420893',
 '190065',
 '294251',
 '329562',
 '96823',
 '299524',
 '351713',
 '95567',
 '287758',
 '441072',
 '255738',
 '79120',
 '257861',
 '228419',
 '204967',
 '223902',
 '300405',
 '383856',
 '103476',
 '38014',
 '76814',
 '112552',
 '149655',
 '326887',
 '35396',
 '389728',
 '290473',
 '226509',
 '97184',
 '79310',
 '88974',
 '145820',
 '78417',
 '384377',
 '435113',
 '7261',
 '108045',
 '227177',
 '153848',
 '227999',
 '79227',
 '165877',
 '121414',
 '306402',
 '402900',
 '27120',
 '280329',
 '426955',
 '8941',
 '198904',
 '351187',
 '430085',
 '48713',
 '282929',
 '50514',
 '173626',
 '82637',
 '245678',
 '4556',
 '159823',
 '379148',
 '149159',
 '181933',
 '196557',
 '190752',
 '414567',
 '392491',
 '86779',
 '389553',
 '183907',
 '430043',
 '385304',
 '33780',
 '99767',
 '391354',
 '306886',
 '5513',
 '149235',
 '149172',
 '47197',
 '213710',
 '438616',
 '121524',
 '112789',
 '329043',
 '30677',
 '271024',
 '432813',
 '188044',
 '339404',
 '277413',
 '360913',
 '395179',
 '97138',
 '438894',
 '194750',
 '412457',
 '352659',
 '38779',
 '104709',
 '139082',
 '130801',
 '389057',
 '69314',
 '92135',
 '90444',
 '367853',
 '287533',
 '359326',
 '159029',
 '208275',
 '90031',
 '83320',
 '229915',
 '436968',
 '121861',
 '85233',
 '236508',
 '413822',
 '288044',
 '430041',
 '50951',
 '213944',
 '82242',
 '9685',
 '367065',
 '306523',
 '195956',
 '392180',
 '58016',
 '319683',
 '80364',
 '28667',
 '387099',
 '183514',
 '122676',
 '256108',
 '171317',
 '441190',
 '345726',
 '122447',
 '192594',
 '256587',
 '369207',
 '398194',
 '150735',
 '345114',
 '1252',
 '430374',
 '378937',
 '76834',
 '351235',
 '278856',
 '406184',
 '345362',
 '105452',
 '154116',
 '58545',
 '198433',
 '274426',
 '131285',
 '292280',
 '409834',
 '100401',
 '191534',
 '367890',
 '299757',
 '43913',
 '219579',
 '405212',
 '342964',
 '186392',
 '147016',
 '222074',
 '264315',
 '358376',
 '377252',
 '428726',
 '319342',
 '47143',
 '171930',
 '346229',
 '109089',
 '225060',
 '57836',
 '193826',
 '393471',
 '56788',
 '280647',
 '261232',
 '161195',
 '60778',
 '52394',
 '218616',
 '322433',
 '159112',
 '25810',
 '421263',
 '295312',
 '264635',
 '16064',
 '386460',
 '129288',
 '414220',
 '78919',
 '54077',
 '434329',
 '347486',
 '357617',
 '141306',
 '44547',
 '408468',
 '410005',
 '13715',
 '19681',
 '102341',
 '129596',
 '169655',
 '81557',
 '201396',
 '49117',
 '246807',
 '440072',
 '55403',
 '217435',
 '251156',
 '378679',
 '336865',
 '259217',
 '6055',
 '422085',
 '435303',
 '317775',
 '192632',
 '9880',
 '83073',
 '403219',
 '350801',
 '151851',
 '260701',
 '235241',
 '249430',
 '342010',
 '47330',
 '6073',
 '224625',
 '71005',
 '48605',
 '419908',
 '113610',
 '148004',
 '198161',
 '10208',
 '305933',
 '164338',
 '280055',
 '19053',
 '237109',
 '320267',
 '93741',
 '193538',
 '154548',
 '253795',
 '20273',
 '33424',
 '113076',
 '223853',
 '128821',
 '3027',
 '440975',
 '437501',
 '156958',
 '257756',
 '318533',
 '86412',
 '128543',
 '40239',
 '430369',
 '167469',
 '378098',
 '392721',
 '126215',
 '161399',
 '39671',
 '382875',
 '354154',
 '129292',
 '18820',
 '179331',
 '98716',
 '87387',
 '295044',
 '225138',
 '134602',
 '238494',
 '283288',
 '65730',
 '51838',
 '244899',
 '401478',
 '343282',
 '320778',
 '423562',
 '265876',
 '437616',
 '438614',
 '103161',
 '406740',
 '325256',
 '416941',
 '176729',
 '218517',
 '243452',
 '289037',
 '439320',
 '28754',
 '404172',
 '333761',
 '412615',
 '247060',
 '316229',
 '178429',
 '430768',
 '419922',
 '129062',
 '378784',
 '51682',
 '224852',
 '141311',
 '158277',
 '377507',
 '6986',
 '122677',
 '24427',
 '217830',
 '152232',
 '79738',
 '165140',
 '55827',
 '219216',
 '53736',
 '329899',
 '374782',
 '220971',
 '60973',
 '143113',
 '235341',
 '184340',
 '380170',
 '410308',
 '405905',
 '345175',
 '804100',
 '82013',
 '378922',
 '392850',
 '404608',
 '176041',
 '11841',
 '296656',
 '11950',
 '265843',
 '321870',
 '66153',
 '133600',
 '270993',
 '22863',
 '304514',
 '362915',
 '14637',
 '16271',
 '160179',
 '151325',
 '277922',
 '190919',
 '257149',
 '263924',
 '328687',
 '330464',
 '250819',
 '219453',
 '386880',
 '208011',
 '392085',
 '294011',
 '199186',
 '257118',
 '293880',
 '22899',
 '420506',
 '296321',
 '149768',
 '71124',
 '4982',
 '20770',
 '294790',
 '339114',
 '123400',
 '92903',
 '23609',
 '102434',
 '435317',
 '323698',
 '1894',
 '357192',
 '178873',
 '49504',
 '380750',
 '200769',
 '408622',
 '297983',
 '92128',
 '126612',
 '67057',
 '389332',
 '92967',
 '361563',
 '405576',
 '416946',
 '282475',
 '32577',
 '84182',
 '190497',
 '383417',
 '84900',
 '328622',
 '425360',
 '139380',
 '243659',
 '352157',
 '90704',
 '395198',
 '83250',
 '137133',
 '35742',
 '426419',
 '8640',
 '162305',
 '279453',
 '283626',
 '126505',
 '169301',
 '383534',
 '229152',
 '327211',
 '348088',
 '59982',
 '239685',
 '289093',
 '290983',
 '75481',
 '291914',
 '149648',
 '436605',
 '29847',
 '259633',
 '356662',
 '394450',
 '334869',
 '246779',
 '439150',
 '217925',
 '358898',
 '258904',
 '406264',
 '261507',
 '257427',
 '146074',
 ...}

In [17]:
interactions_list = []

with open("./dataset/goodreads_interactions.csv") as f:
    while True:
        line = f.readline()
        if not line:
            break

        user_id, csv_id, _, rating, _ = line.strip().split(',')
        if user_id in filtered_overlap_users:
            book_id = csv_book_mapping[csv_id]
            interactions_list.append([user_id, book_id, rating])